enabled: true
filter_simple_trials: false
filter_incongruent: false

filter_by_length:
  enabled: false
  min_length: 100
  max_length: 150

select_channels:
  enabled: true
  channels:
    - Fp1
    - Fpz
    - Fp2
    - AF7
    - AF3
    - AF4
    - AF8
    - F7
    - F5
    - F3
    - F1
    - Fz
    - F2
    - F4
    - F6
    - F8
    - FT7
    - FC5
    - FC3
    - FC1
    - FCz
    - FC2
    - FC4
    - FC6
    - FT8
    - T7
    - C5
    - C3
    - C1
    - Cz
    - C2
    - C4
    - C6
    - T8

response_locking: false

truncate:
  enabled: false
  start_timepoint: 0
  end_timepoint: 256

handle_nans: false
normalize_per_trial: true
