enabled: true
filter_simple_trials: false
filter_incongruent: false

filter_by_length:
  enabled: false
  min_length: null
  max_length: null

select_channels:
  enabled: true
  # Frontal and Central electrodes for EEGPT
  channels: ['FP1', 'FPZ', 'FP2', 'AF7', 'AF3', 'AF4', 'AF8', 'F7', 'F5', 'F3', 'F1', 'FZ', 'F2', 'F4', 'F6', 'F8', 'FT7', 'FC5', 'FC3', 'FC1', 'FCZ', 'FC2', 'FC4', 'FC6', 'FT8', 'C5', 'C3', 'C1', 'CZ', 'C2', 'C4', 'C6']

response_locking: false

truncate:
  enabled: true
  start_timepoint: 0
  end_timepoint: 64

handle_nans: false
normalize_per_trial: true
