type: eegpt

eegpt:
  # Architecture
  patch_stride: 64
  use_chan_conv: true
  interpolate_factor: 2.0
  desired_time_len: 256

  # Regularization
  max_norm_chan_conv: 1
  max_norm_head: 0.5
  qkv_bias: true
  enc_drop_rate: 0.1
  enc_attn_drop_rate: 0.1
  enc_drop_path_rate: 0.1
  rec_drop_rate: 0.1
  rec_attn_drop_rate: 0.1
  rec_drop_path_rate: 0.1
  use_freeze_encoder: true

  # Pretrained checkpoint loading
  load_pretrained: true
  pretrained_checkpoint: /ems/elsc-labs/kadmon-j/gilad.ticher/eeg-classification/checkpoints/eegpt_mcae_58chs_4s_large4E.ckpt
