defaults:
  - training: default
  - task: right_left
  - model: cnn
  - preprocessing: default
  - _self_

task: right_left
seed: 42
device: cuda

data:
  data_dir: ../eeg-classification/data/raw/09_25_256hz
  batch_size: 64
  val_split: 0.1
  test_split: 0.1
  n_folds: 1

preprocessing:
  filter_simple_trials: true

wandb:
  enabled: true
  project: eeg-classification
  entity: null
  mode: online
